//
//  nanoKontrolConstants.h
//  d4nSFPCRunner
//
//  Created by Roy Macdonald on 16-12-15.
//
//

#pragma once

#define NANO_KONTROL_KEY_REW 43
#define NANO_KONTROL_KEY_FFW 44
#define NANO_KONTROL_KEY_STOP 42
#define NANO_KONTROL_KEY_PLAY 41
#define NANO_KONTROL_KEY_REC 45
#define NANO_KONTROL_KEY_CICLE 46
#define NANO_KONTROL_KEY_TRACK_PREV 58
#define NANO_KONTROL_KEY_TRACK_NEXT 59
#define NANO_KONTROL_KEY_MARKER_SET 60
#define NANO_KONTROL_KEY_MARKER_PREV 61
#define NANO_KONTROL_KEY_MARKER_NEXT 62
#define NANO_KONTROL_START_SLIDER 0
#define NANO_KONTROL_START_KNOB 16
#define NANO_KONTROL_START_R 64
#define NANO_KONTROL_START_M 48
#define NANO_KONTROL_START_S 32